### ISSUE TITLE
NPM everdev package doesn't show Warnings and Notes

### ISSUE THREAD

**Issue by pizza-777** [tonlabs/everdev#98]
**Problem description.**

I am using the evedev package in my vscode extension. And when I compile a contract I need to catch errors and warnings, notes too. But everdev from npm only shows errors. At the same time, the evedev in the console shows all: errors, warnings and notes.

**Comment by ilyar** [comment]
https://github.com/tonlabs/everdev/pull/82  must publish new version https://www.npmjs.com/package/everdev

**Comment by elasticLove1** [comment]
@pizza-777 Can you please describe expected and factual behaviour, like this:

1. I do this and that(describe your commands, and all the relevant), and get this behavous:
2. Copy logs here of the behaviour you get
3. The expected behaviour is + 
Copy original solidity logs here  so that we know where the warnings are not recorded. The last time we checked, we saw that warnings were printed. 
Thank you:)

**Comment by pizza-777** [comment]
🤦 It was a mistake in my script.
